### ISSUE TITLE
'module' object has no attribute 'init'

### ISSUE THREAD

**Issue by dgasaway** [kdeldycke/mail-deduplicate#63]
```
# pip3 install --user maildir-deduplicate
[...]
Successfully installed boltons-18.0.0 click-6.7 click-log-0.2.1 maildir-deduplicate-2.1.0 progressbar2-3.37.1 python-utils-2.3.0 tabulate-0.8.2
```
```
# ~/.local/bin/mdedup --help
Traceback (most recent call last):
  File "/root/.local/bin/mdedup", line 7, in <module>
    from maildir_deduplicate.cli import cli
  File "/root/.local/lib64/python3.4/site-packages/maildir_deduplicate/cli.py", line 51, in <module>
    @click_log.init(logger)
AttributeError: 'module' object has no attribute 'init'
```
```
# python3 --version
Python 3.4.6
# pip3 --version
pip 9.0.1 from /usr/lib64/python3.4/site-packages (python 3.4)
```

This is on a funtoo system.  Used `--user` so that dependencies wouldn't collide with package manager.

**Comment by orlyapps** [comment]
same problem - any help?

**Comment by fragtion** [comment]
Same problem here. installed fresh via pip

**Comment by MarcvdSluys** [comment]
@fragtion Did you publish your patched version somewhere?

**Comment by fragtion** [comment]
@MarcvdSluys Unfortunately can't recall what I did with my changes to source as it's no longer installed via pip nor in my sources folder on my server

According to @bvbmedia at #58 , the problem can be resolved by using the develop branch. See his comment for build instructions (in particular, `python setup.py develop`)

FWIW I've cloned @baip's fork to https://github.com/fragtion/maildir-deduplicate, but made no further changes yet.  IIRC, I had to merge the changes to lines 51,52,59 described in #58 in order to get his master fork to work (didn't work on @kdeldycke's master), but it seems this is not necessary if develop works for this repo

Please let us know if you succeed or not :)

**Comment by rjayasinghe** [comment]
Reason for this bug is, that the version range for click-log is specified to be larger than 0.2.0 which is kind of open end: https://github.com/kdeldycke/maildir-deduplicate/blob/f1c6ff25b80c6c1a4dc2dc7a65b34d808b0b7733/setup.py#L41

It seems that click-log in some later version had breaking changes which break this tool. :)

**Comment by ZaxonXP** [comment]
Installed today from pip and I have the same issue. What to do next?

**Comment by rjayasinghe** [comment]
> Installed today from pip and I have the same issue. What to do next?

I gave up with the tool and removed the duplicates with a Thunderbird plugin :innocent:

**Comment by ZaxonXP** [comment]
I found some better way to find a duplicates across many maildirs:
```
find ~/Mail/GMail/ -type d -name cur -print0 | xargs -0 /usr/bin/fdupes -n > mail_dups.txt
```

**Comment by jackm** [comment]
> I found some better way to find a duplicates across many maildirs:
> 
> ```
> find ~/Mail/GMail/ -type d -name cur -print0 | xargs -0 /usr/bin/fdupes -n > mail_dups.txt
> ```

Using this method with fdupes only works when the compared files are _exactly_ the same (i.e. md5 hashes match, byte-for-byte the same). This does not account for minor changes in headers, additional footers, etc

**Comment by kdeldycke** [comment]
This issue has been solved with the update to latest `click-log` package. See: https://github.com/kdeldycke/mail-deduplicate/commit/3c30b0fb49f0fe9d962d31b1b463ad93216c1b69

`mail-deduplicate` has been extensively rewritten and is now better packaged.

**Comment by kdeldycke** [comment]
For the record, this has been duplicated in #65.
